import Head from 'next/head'
import { Maven_Pro } from 'next/font/google'
import { useState } from "react"
import ChatWindow from "@/components/chat-window"

const mavenPro = Maven_Pro({ subsets: ['latin'] })

export default function Home() {
    // const [prompts, setPrompts] = useState([])
    //
    // async function fetchPrompts() {
    //     const res = await fetch('/api/prompts')
    //     const data = await res.json()
    //     setPrompts(data)
    // }

    return (
        <>
            <Head>
                <title>Robspin GPT</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <main className={`h-screen p-4 bg-slate-900 ${mavenPro.className}`}>
                <div className="h-full flex w-full flex-col">
                    <div className="h-40 w-full bg-red-50">

                    </div>
                    <ChatWindow />
                </div>
            </main>
        </>
    )
}
