import Head from 'next/head'
import { Maven_Pro } from 'next/font/google'
import ChatWindow from "@/components/chat-window"
import Avatar from "@/components/avatar"

const mavenPro = Maven_Pro({ subsets: ['latin'] })

export default function Home() {

    return (
        <>
            <Head>
                <title>Robspin GPT</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <main className={`h-screen flex justify-center bg-black ${mavenPro.className}`}>
                <div className="h-full grid grid-rows-3 w-[416px] bg-slate-900 px-4 py-2 border-slate-700 border rounded text-center">
                    <Avatar />
                    <ChatWindow />
                </div>
            </main>
        </>
    )
}
